### ISSUE TITLE
IIS 服务器载入模型会 404？

### ISSUE THREAD

**Issue by Taskeren** [Dreamer-Paul/Pio#1]
显示不出来，然后看console说是读取文件404，emmm。

**Comment by Dreamer-Paul** [comment]
你的插件目录设置正确了吗？需要改成 `Pio` 才行

**Comment by Taskeren** [comment]
关于文件无法载入导致无法显示的解决方法
特征： 在 F12 里的 Console 中会显示关于文件载入失败或者404。访问 JSON 显示 404.3 错误。
解决方案：在服务器的 MIME 映射中添加对应的映射
.json 对应 application/json
.moc 对应 text/plain
.mtn 对应 text/plain
.png 对应 image/png（正常服务器都有这个的吧，如果连 PNG 的 MIME 映射都没有，那还算什么Web服务器嘛！）

**Comment by ghost** [comment]
> 你的插件目录设置正确了吗？需要改成`Pio`才行

为什么我这样设置了不可以啊

**Comment by Dreamer-Paul** [comment]
> > 你的插件目录设置正确了吗？需要改成`Pio`才行
> 
> 为什么我这样设置了不可以啊

麻烦说明一下具体情况，也可以加群交流
