### ISSUE TITLE
隐藏看板娘看上去并不起作用

### ISSUE THREAD

**Issue by KevinZonda** [Dreamer-Paul/Pio#11]
### 1. 该问题的重现步骤是什么？

在手机上进行浏览。

### 2. 正常情况下的结果如何，你看到的呢？

在隐藏看板娘开启时，依旧会出现模型

### 3. 服务器的运行环境是？

- 操作系统版本：Debian9 x64
- Apache/Nginx 版本：Nginx 1.17
- PHP 版本：7.2
- 插件版本：2.4
- 浏览器版本：Brave 1.6.0， Chromium 78.0.3904.108

[//]: # (如有图片请附上截图)
![插件设置](https://user-images.githubusercontent.com/33132228/76138983-18bb4900-6087-11ea-9baa-a0cbb2699a43.png)
![访问情况](https://user-images.githubusercontent.com/33132228/76139009-515b2280-6087-11ea-95d6-ee63b1460244.png)

**Comment by Dreamer-Paul** [comment]
麻烦提供一下站点地址，我看看是什么情况？

**Comment by KevinZonda** [comment]
> 麻烦提供一下站点地址，我看看是什么情况？

https://www.moekevin.com

**Comment by Dreamer-Paul** [comment]
已经确认问题了，其实是检测手机的方法不够合理，只要屏幕分辨率大于 400 像素是看板娘就会显示
