### ISSUE TITLE
能否设置%t值无效就使用时间小提示？

### ISSUE THREAD

**Issue by copurxia** [Dreamer-Paul/Pio#14]
%t 值无效就只显示 “%t”有点奇怪

**Comment by Dreamer-Paul** [comment]
你的意思是想让时间小贴士直接替代掉默认的入站提示吗？这个只需要设置 `tips` 属性就可以了呀。`%t` 值无效，我不明白为什么要它无效

**Comment by copurxia** [comment]
我是指%t 有效的时候用入站提示，无效的时候用时间小贴士

**Comment by copurxia** [comment]
问题已解决
