### ISSUE TITLE
更多选项的自定义位置

### ISSUE THREAD

**Issue by liucan233** [Dreamer-Paul/Pio#16]
可不可以更进一步自定义位置呢，例如https://blog.ieleven.xyz:63363/ 
![ideal](https://user-images.githubusercontent.com/13808186/86005251-f474e500-ba46-11ea-8b28-983106187f55.JPG)
右上角合理的位置

**Comment by Dreamer-Paul** [comment]
你好，并不是每个主题都有相同高度的顶栏和位置，你可以尝试先自己修改插件的 `pio.css` 文件实现效果。将 `.pio-container` 选择器下的 `bottom: 0` 属性移除，并替换成 `top: 3em` 就可以了噢
