### ISSUE TITLE
点击 X 按钮之后无法再次让模型出现

### ISSUE THREAD

**Issue by zhouguannan** [Dreamer-Paul/Pio#17]
### 1. 该问题的重现步骤是什么？
展现模式调成固定后点击x按钮后无法再次调出模型

### 2. 服务器的运行环境是？

- 操作系统版本：ubuntuserver20.04
- Apache/Nginx 版本：1.15
- PHP 版本：5.4
- 插件版本：2.4
- 浏览器版本：chrome/firefox

[//]: # (如有图片请附上截图)

**Comment by Dreamer-Paul** [comment]
老早的问题了，其实也没有什么好的方案，唯独的办法就是加一个图片作为替代品
