### ISSUE TITLE
能否增加自定义边距功能

### ISSUE THREAD

**Issue by Xunflash** [Dreamer-Paul/Pio#19]
### 1. 该问题的重现步骤是什么？
设置两个皮肤的情况下，设置中自定义宽高度无法保证两个模型完美显示

![image](https://user-images.githubusercontent.com/71567536/113305193-5f847c80-9335-11eb-8070-d5506c912209.png)

![image](https://user-images.githubusercontent.com/71567536/113305292-74611000-9335-11eb-85dc-63e87f431656.png)

鼠标移动的时候总有一部分被截掉，如果能自定义透明边框，就可以全部包含模型部分了

### 2. 正常情况下的结果如何，你看到的呢？
如上图
### 3. 服务器的运行环境是？
php7，sqlite3，nginx
- 操作系统版本：Windows10
- Apache/Nginx 版本：--
- PHP 版本：7
- 插件版本：最新
- 浏览器版本：89.0.4389.114

[//]: # (如有图片请附上截图)

**Comment by Dreamer-Paul** [comment]
不能用开发工具改宽高的哦，被截取一般是宽高比例没设置好造成的...

如果你把宽高改的很大，模型会缩放还是一样大呢？

**Comment by Xunflash** [comment]
> 不能用开发工具改宽高的哦，被截取一般是宽高比例没设置好造成的...
> 
> 如果你把宽高改的很大，模型会缩放还是一样大呢？

会缩放的

**Comment by Dreamer-Paul** [comment]
你可以直接修改 css 里面的 left 试试？
