### ISSUE TITLE
模型使用

### ISSUE THREAD

**Issue by LovesAsuna** [Dreamer-Paul/Pio#22]
### 1. 该问题的重现步骤是什么？
https://github.com/Eikanya/Live2d-model下载模型后导入，并稍加修改model.json
### 2. 正常情况下的结果如何，你看到的呢？
看不到模型
### 3. 服务器的运行环境是？
Centos
- 操作系统版本：CentOS Linux release 7.6.1810 (Core)
- Apache/Nginx 版本：nginx/1.18.0
- PHP 版本：PHP 7.2.34
- 插件版本：2.4
- 浏览器版本：Google Chrome 90.0.4430.93

![13IL$F0AK`B5V0CWUKF65B4](https://user-images.githubusercontent.com/32810896/117529337-aa1aa800-b009-11eb-8743-6ad6e8efa665.png)

我觉得是模型版本问题，插件默认的model.json是v1
而给的model是v3的

**Comment by Dreamer-Paul** [comment]
主分支确实不支持 v3 模型呀，你发之前没看到下面的 Issues 么...

想要用 v3 的话可以看看插件的 dev_v3 分支，捣鼓一下

**Comment by LovesAsuna** [comment]
太难顶了，看了那个文章是基于live2d官方给出的WordPress插件然后那个项目已经删除了，自己也不会捣鼓
