### ISSUE TITLE
用血小板不能蹦蹦跳跳的

### ISSUE THREAD

**Issue by swordstudiox** [Dreamer-Paul/Pio#6]
用的这个方法转的血小板模型：https://imjad.cn/archives/lab/add-dynamic-poster-girl-with-live2d-to-your-blog-03
模型文件链接：https://file.agint.me/typecho%E6%8F%92%E4%BB%B6/kesshouban_v2.1.rar
用上去以后不能像imjad.cn博客那样点击蹦蹦跳跳，我的博客地址：https://agint.me/

**Comment by Dreamer-Paul** [comment]
经过实访，你的控制台报错信息为找不到 `mtn` 动作文件，为模型问题，插件没有任何问题。

**Comment by swordstudiox** [comment]
现在还是不能蹦蹦跳跳的，没有报错了
https://sword.studio/
