### ISSUE TITLE
跨域了，怎么解决

### ISSUE THREAD

**Issue by akFace** [Dreamer-Paul/Pio#8]
用的是虚拟主机，
如图，不带www的异常，显示不了
![image](https://user-images.githubusercontent.com/22288837/62388401-d4ffde80-b58f-11e9-9f62-b56b39db3536.png)

**Comment by akFace** [comment]
模型出不来，只有按钮
![image](https://user-images.githubusercontent.com/22288837/62388486-07a9d700-b590-11e9-8945-ebaf20a34805.png)

**Comment by Dreamer-Paul** [comment]
个人建议你不要同时使用两个域名，可以通过跳转的方式指向其中一个即可。若要坚持这样使用的话，你可以尝试在虚拟主机的后台找找有没有修改主机头相关的功能，这个在 [插件文档](https://docs.paul.ren/pio) 上有相关的解决方案

**Comment by akFace** [comment]
> 个人建议你不要同时使用两个域名，可以通过跳转的方式指向其中一个即可。若要坚持这样使用的话，你可以尝试在虚拟主机的后台找找有没有修改主机头相关的功能，这个在 [插件文档](https://docs.paul.ren/pio) 上有相关的解决方案

多谢！我试试
